[package]
name = "day04"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.2"
utils = { path = "../utils" }

[lints]
workspace = true
