[package]
name = "day07"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
intcode = { path = "../intcode" }
itertools = "0.14.0"


[lints]
workspace = true
